// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"FixCollisionBug","status":true,"description":"When placing a passable tile on top of a non-passable tile, the RMMZ allows movement onto the tile, when instead it should prevent movement on to the tile.","parameters":{}}
];
